//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.10.1.0 (NJsonSchema v10.3.3.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"

namespace JG.FinTech.GiftAid.Api.Controllers
{
    using System = global::System;
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.10.1.0 (NJsonSchema v10.3.3.0 (Newtonsoft.Json v11.0.0.0))")]
    public interface IGiftAidController
    {
        /// <summary>Get the amount of gift aid reclaimable for donation amount</summary>
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<GiftAidResponse> GiftaidAsync(double amount);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.10.1.0 (NJsonSchema v10.3.3.0 (Newtonsoft.Json v11.0.0.0))")]
    [Microsoft.AspNetCore.Mvc.Route("api")]
    public partial class GiftAidController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IGiftAidController _implementation;
    
        public GiftAidController(IGiftAidController implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Get the amount of gift aid reclaimable for donation amount</summary>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("giftaid")]
        public System.Threading.Tasks.Task<GiftAidResponse> Giftaid([Microsoft.AspNetCore.Mvc.FromQuery] double amount)
        {
            return _implementation.GiftaidAsync(amount);
        }
    
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.3.3.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class GiftAidResponse 
    {
        [Newtonsoft.Json.JsonProperty("donationAmount", Required = Newtonsoft.Json.Required.Always)]
        public double DonationAmount { get; set; }
    
        [Newtonsoft.Json.JsonProperty("giftAidAmount", Required = Newtonsoft.Json.Required.Always)]
        public double GiftAidAmount { get; set; }
    
    
    }

}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108